name = "rxada"
description = "Experimental implementation of ReactiveX in Ada"
version = "0.1.1"
licenses = "LGPL-3.0-only"
website = "https://github.com/mosteo/rxada"

tags = ["rx", "reactive", "reactivex", "observer"]

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

[configuration]
disabled = true
